apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: <%= pipelineName %>
  namespace: <%= pipelineName %>-namespace
spec:
  description: | 
    This pipeline clones a git repo and builds a Spring Boot
  params:
  - name: repo-url
    type: string
  - name: revision
    type: string
  - name: submodules
    type: string
  - name: directory
    type: string
  - name: image-reference
    type: string
  - name: maven-image-reference
    type: string

  workspaces:
  - name: shared-data
  - name: docker-credentials
  - name: ssh-creds

  tasks:
  - name: clone-spring-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    - name: ssh-directory
      workspace: ssh-creds
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.revision)
    - name: submodules
      value: $(params.submodules)
  - name: jib-maven
    taskRef:
      name: jib-maven
    runAfter: ["clone-spring-repo"]
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: IMAGE
      value: $(params.image-reference)
    - name: DIRECTORY
      value: $(params.directory)
    - name: MAVEN_IMAGE
      value: $(params.maven-image-reference)