apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: <%= pipelineName %>-run-
  namespace: <%= pipelineName %>-namespace
spec:
  serviceAccountName: <%= pipelineName %>-service-account
  pipelineRef:
    name: <%= pipelineName %>

  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  - name: ssh-creds
    secret:
      secretName: git-sshkey-secret

  params:
  - name: repo-url
    value: <%= repoURL %>
  - name: revision
    value: <%= branch %> 
  - name: submodules
    value: "false"
  - name: image-reference
    value: <%= imageURL %>
  - name: context
    value: <%= PathtoContext %>
  - name: dockerfile
    value: $(workspaces.source.path)/<%= PathtoDockerfile %>
  - name: maven-image-reference
    value: lokeshkarakala/custom-dev-image