apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: go-pipeline-run-
  namespace: go-pipeline-namespace
spec:
  pipelineRef:
    name: go-pipeline

  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials

  params:
  - name: repo-url
    value: git@github.com:Nandiniperikala/private.git
  - name: revision
    value: main 
  - name: image-reference
    value: nandinikarthik14/go:latest
  serviceAccountName: go-pipeline-service-account