apiVersion: v1
kind: ServiceAccount
metadata:
  name: ticgo-pipeline-service-account
  namespace: ticgo-pipeline-namespace
secrets:
  - name: git-sshkey-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-ticgo-pipeline-role
  namespace: ticgo-pipeline-namespace
rules:
# EventListeners need to be able to fetch all namespaced resources
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers", "interceptors"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
# configmaps is needed for updating logging config
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames: ["tekton-triggers"]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-ticgo-pipeline-binding
  namespace: ticgo-pipeline-namespace
subjects:
- kind: ServiceAccount
  name: ticgo-pipeline-service-account
  namespace: ticgo-pipeline-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-ticgo-pipeline-role
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-ticgo-pipeline-clusterrole
  namespace: ticgo-pipeline-namespace
rules:
  # EventListeners need to be able to fetch any clustertriggerbindings
- apiGroups: ["triggers.tekton.dev"]
  resources: ["clustertriggerbindings", "clusterinterceptors", "interceptors"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-ticgo-pipeline-clusterbinding
  namespace: ticgo-pipeline-namespace
subjects:
- kind: ServiceAccount
  name: ticgo-pipeline-service-account
  namespace: ticgo-pipeline-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-ticgo-pipeline-clusterrole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-ticgo-pipeline-kubectl-role
  namespace: ticgo-pipeline-namespace
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  - deployments
  - deployments/scale
  - deployments/status
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-ticgo-pipeline-kubectl-binding
  namespace: ticgo-pipeline-namespace
subjects:
- kind: ServiceAccount
  name: ticgo-pipeline-service-account
  namespace: ticgo-pipeline-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-ticgo-pipeline-kubectl-role

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ticgo-pipeline-namespace
  name: tekton-ticgo-pipeline-ssh-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-ticgo-pipeline-ssh-binding
  namespace: ticgo-pipeline-namespace
subjects:
- kind: ServiceAccount
  name: ticgo-pipeline-service-account
  namespace: ticgo-pipeline-namespace
roleRef:
  kind: Role
  name: tekton-ticgo-pipeline-ssh-role
  apiGroup: rbac.authorization.k8s.io