apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: azure-pipeline-trigger-binding
  namespace: azure-pipeline-namespace
spec:
  params:
  - name: revision
    value: $(body.head_commit.id)
  - name: repo-url
    value: git@github.com:Nandiniperikala/spring.git
  - name: submodules
    value: "false"
  - name: image-reference
    value: ticacr.azurecr.io/azure-go:latest
  - name: context
    value: go
  - name: dockerfile
    value: go/Dockerfile
  
---

apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: azure-pipeline-trigger-template
  namespace: azure-pipeline-namespace
spec:
  params:
  - name: revision
    default: main
  - name: repo-url
  - name: image-reference
  - name: submodules
  - name: dockerfile
  - name: context
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: azure-pipeline-run-
    spec:
      serviceAccountName: azure-pipeline-service-account
      pipelineRef:
        name: azure-pipeline
      podTemplate:
        securityContext:
          fsGroup: 65532 
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
      - name: docker-credentials
        secret:
          secretName: docker-credentials
      - name: ssh-creds
        secret:
          secretName: git-sshkey-secret
          
      params:
      - name: repo-url
        value: $(tt.params.repo-url)
      - name: revision
        value: $(tt.params.revision)
      - name: submodules
        value: $(tt.params.submodules)
      - name: image-reference
        value: $(tt.params.image-reference)
      - name: context
        value: $(tt.params.context)
      - name: dockerfile
        value: $(tt.params.dockerfile)