apiVersion: v1
kind: Secret
metadata:
  name: git-sshkey-secret
  namespace: go-pipeline-namespace
data:
  id_rsa: <paste your encoded value of ssh-private-key>
  config: <paste your encoded value of ssh_config>