---

apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: tekton-namespace
data:
  config.json: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICJhdXRoIjogImNtRjRhM1Z0WVhJNlVtRnJaWE5vUURFM01UST0iCiAgICAgICAgfQogICAgfQp9