apiVersion: v1
kind: Secret
metadata:
  name: git-sshkey-secret
  namespace: <%= namespaceName %>
data:
  id_rsa: <%= deployKey %>
  config: <%= sshConfig %>

---

apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: <%= namespaceName %>
data:
  config.json: <%= dockerConfig %>