apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: <%= pipelineName %>-trigger-binding 
  namespace: <%= pipelineName %>-namespace
spec:
  params:
  - name: revision
    value: $(body.head_commit.id)
  - name: repo-url
    value: <%= repoURL %>
  <%_ if (registry == "docker-hub") { _%>
  - name: image-reference
    value: <%= registryName %>/<%= imageName %>:latest
  <%_ } _%>
  <%_ if (registry == "acr") { _%>
  - name: image-reference
    value: <%= registryName %>.azurecr.io/<%= imageName %>:latest
  <%_ } _%>
  <%_ if (registry == "ecr") { _%>
  - name: image-reference
    value: <%= registryURI %>/<%= imageName %>:latest
  <%_ } _%>
  <%_ if (registry == "git-package") { _%>
  - name: image-reference
    value: nandinikarthik14/go:latest
  <%_ } _%>
  - name: maven-image-reference
    value: lokeshkarakala/custom-dev-image
  
---

apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: <%= pipelineName %>-trigger-template
  namespace: <%= pipelineName %>-namespace
spec:
  params:
  - name: revision
    default: <%= branch %>
  - name: maven-image-reference
  - name: repo-url
  - name: image-reference
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: <%= pipelineName %>-run-
    spec:
      serviceAccountName: <%= pipelineName %>-service-account
      pipelineRef:
        name: <%= pipelineName %>
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      - name: docker-credentials
        secret:
          secretName: docker-credentials
      - name: ssh-creds
        secret:
          secretName: git-sshkey-secret
      
      params:
      - name: repo-url
        value: $(tt.params.repo-url)
      - name: revision
        value: $(tt.params.revision)
      - name: image-reference
        value: $(tt.params.image-reference)
      - name: maven-image-reference
        value: $(tt.params.maven-image-reference)
      