apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: go-pipeline-eventlistener
  namespace: go-pipeline-namespace
spec:
  serviceAccountName: go-pipeline-service-account
  triggers:
    - name: go-pipeline-trigger
      bindings:
        - ref: go-pipeline-trigger-binding
      template:
        ref: go-pipeline-trigger-template



