apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: k8s-pipeline-eventlistener
  namespace: k8s-namespace
spec:
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
  serviceAccountName: k8s-pipeline-service-account
  triggers:
    - name: k8s-pipeline-trigger
      bindings:
        - ref: k8s-pipeline-trigger-binding
      template:
        ref: k8s-pipeline-trigger-template



