apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: go-pipeline-trigger-binding
  namespace: go-pipeline-namespace
spec:
  params:
  - name: revision
    value: $(body.head_commit.id)
  - name: repo-url
    value: git@github.com:Nandiniperikala/private.git
  - name: image-reference
    value: nandinikarthik14/new-go:latest
  
---

apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: go-pipeline-trigger-template
  namespace: go-pipeline-namespace
spec:
  params:
  - name: revision
    default: main
  - name: repo-url
  - name: image-reference
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: go-pipeline-run-
    spec:
      pipelineRef:
        name: go-pipeline
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      - name: docker-credentials
        secret:
          secretName: docker-credentials
      - name: ssh-creds
        secret:
          secretName: git-sshkey-secret
      
      params:
      - name: repo-url
        value: $(tt.params.repo-url)
      - name: revision
        value: $(tt.params.revision)
      - name: image-reference
        value: $(tt.params.image-reference)
      